api_version: v1
device:
  id: "PICAM-0001"
  model: "PiCam-Full"
  hw_rev: "A1"
  fw_version: "0.2.0"
capabilities:
  video: True
  audio: True  # Enable audio
  gnss: True
  storage: True
api:
  host: "0.0.0.0"
  port: 8081
  api_key: "change-this-api-key"
webui:
  host: "0.0.0.0"
  port: 8080
paths:
  record_root: /media/ssd
  log_dir: /media/ssd
storage:
  min_free_gb: 1.0
  segment_seconds: 30
  container: mkv
  filename_pattern: "%Y%m%d-%H%M%S.mkv"
video:
  v4l2_device: "/dev/video0"
  v4l2_format: "640x480"
  v4l2_fps: 15
audio:
  device: "plughw:1,0"  # USB Audio Device (card 1) - use hw instead of plughw
  sample_rate: 48000
  channels: 1
overlay:
  timestamp_font: "/usr/share/fonts/Truetype/dejavu/DejaVuSansMono.ttf"
  timestamp_size: 24
  timestamp_position: "x=w-tw-16:y=h-th-16"
gpio:
  record_led: 26
  wifi_led: 13
  lte_led: 6
  gps_led: 5
  reed: 17
  factory: 27
wifi:
  ssid: "PICAM"
  psk: "0123456789"
  iface: "wlan0"
  idle_seconds: 30
  connect_timeout: 60
lte:
  enabled: True
  iface: "wwan0"
  provider: "auto"
gnss:
  enabled: True
  port: "/dev/ttyACM0"
  baud: 9600